server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: company_service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/companies/**
        - id: job_service
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/jobs/**
        - id: review_service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway: TRACE