server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: chinu
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
